### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by vtmocanu** [bahamas10/zincrsend#1]
Hi,
First of all a big thanks for sharing this!
Can you please also include a cleanup section for the snapshots?
I have created the following steps, however I don't know how/if it will work with multiple datasets:
	# Step 4: clean the snapshots
	echo
	echo "Delete older snaps (grep -v inverts the selection)..."
	delete_from=$(zfs list -H -o name -t snapshot -r "$datasets_recursive" | grep "$snapshot_prefix" | grep -v "$snap")
	for snap in $delete_from; do
    	        zfs destroy "$snap"
		SSH zfs destroy "$snap"
	done

**Comment by bahamas10** [comment]
Hi, I'm glad you are getting use out of this script!

Have you seen the [notes](https://github.com/bahamas10/zincrsend#notes) section of the readme? I have a separate script I used to remove snapshots as they pass a certain age.

**Comment by bahamas10** [comment]
See the blog post here http://daveeddy.com/2015/12/05/automatic-zfs-snapshots-and-backups/

and this snipped specifically

```
9  11 * * * /opt/custom/bin/zfs-prune-snapshots -p zincrsend_ 1M >> /var/log/zincrsend.log 2>&1
10 11 * * * /opt/custom/bin/zincrsend >> /var/log/zincrsend.log 2>&1'
```

**Comment by vtmocanu** [comment]
Wow, another handy zfs script!
Totally missed that section, thanks again!

PS: quick question, a bit offtopic: what happens if zincrsend get interupped during the send/recv?
I guess it's ok as long as one does not remove the snapshot that was just created and you would have to manually send/recv.

**Comment by bahamas10** [comment]
@WladyX I haven't tested that too thoroughly, but I would imagine that running `zinrcsend` again shouldn't have any problems sending.  If it does, you may need to delete snapshots on the *remote* side until they local and remote side have the same snapshots, and then run `zincrsend`
